### ISSUE TITLE
运行到微信开发工具中图标不显示

### ISSUE THREAD

**Issue by aiyunyuner** [xbmlz/echarts-for-uniapp#4]
使用示例代码不成功，同时报错。
![图片](https://user-images.githubusercontent.com/63837650/229097997-7da9c1a3-5709-4a97-8bc6-14b6c7bfce46.png)
![图片](https://user-images.githubusercontent.com/63837650/229098144-459e664b-99af-45da-849b-5793b185aa8f.png)

**Comment by xuanweiH** [comment]
作者感觉已经修了，但是他那个插件库里没更新最新的代码。你去把他分支里的uni-chart文件替换一下就可以使用了
